- type: job
  id: HColonel
  name: job-name-hcolonel
  description: job-description-hcolonel
  displayWeight: 60
  playTimeTracker: JobHColonel
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: HeresyColonelGear
  icon: "JobIconHColonel"
  supervisors: job-supervisors-wh40k-chaos-leader
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: WH40KSquadLeader
      - type: WH40KChaosGiftRole
      - type: WH40KChaosLeaderRole
  access:
  - Maintenance
  - External
  - Command
  - Medical
  - Cargo
  - Engineering
  - Research

- type: startingGear
  id: HeresyColonelGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCultist1
    gloves: ClothingHandsGlovesCombatcult
    shoes: ClothingShoesChaosBoots2
    ears: ClothingHeadsetVoxBackpackHeretics
    outerClothing: ClothingOuterArmorHeresiarchChaos
    belt: chaosbelt
    head: ClothingHeadHelmetFlakAdvHeresy
    pocket1: WH40KCommandTacticalMapTablet
    id: HColonelDogTag
  inhand:
    - ChaosMachete
