- type: job
  id: TitheSupplier
  name: job-name-tithe-supplier
  description: job-description-tithe-supplier
  displayWeight: 40
  playTimeTracker: JobTitheSupplier
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
      - Felinid
  startingGear: TitheSupplierGear
  icon: "JobIconCargo"
  supervisors: job-supervisors-wh40k-imperium-munitorum
  canBeAntag: false
  access:
  - Maintenance
  - External
  - Cargo

- type: job
  id: MunitorumOfficer
  name: job-name-munitorum-officer
  description: job-description-munitorum-officer
  displayWeight: 90
  playTimeTracker: JobMunitorumOfficer
  requirements:
    - !type:SpeciesRequirement
      species:
      - Tau
      inverted: true
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
      - Felinid
  startingGear: MunitorumOfficerGear
  icon: "JobIconCargoOfficer"
  supervisors: job-supervisors-wh40k-imperium-munitorum
  canBeAntag: false
  access:
  - Maintenance
  - External
  - Command
  - Cargo

- type: startingGear
  id: TitheSupplierGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGuardsman
    back: ClothingBackpackGuard
    shoes: ClothingShoesAnkleBoots
    belt: guardbelt
    head: ClothingHeadHelmetFlak
    ears: ClothingHeadsetVoxBackpackImperium
    outerClothing: ClothingOuterArmorMunitorumVest
    pocket1: WH40KStandardTacticalMapTablet
    id: TitheSupplierDogTag

- type: startingGear
  id: MunitorumOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitGuardsman
    back: ClothingBackpackGuard
    shoes: ClothingShoesAnkleBoots
    belt: guardbelt
    head: ClothingHeadHelmetFlak
    ears: ClothingHeadsetVoxBackpackImperium
    outerClothing: ClothingOuterArmorMunitorumCoat
    pocket1: WH40KStandardTacticalMapTablet
    id: MunitorumOfficerDogTag
